import axios from 'axios';

export const UPDATE_DONATION_AMOUNT = 'UPDATE_DONATION_AMOUNT';
export const CLEAR_DONATION = 'CLEAR_DONATION';
//login actions
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
//sign up actions
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';

export const CLEAR_ERROR_STATUS = 'CLEAR_ERROR_STATUS';
// fetch projects
export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
// add projects
export const ADDPROJECT_START = 'ADDPROJECT_START';
export const ADDPROJECT_SUCCESS = 'ADDPROJECT_SUCCESS';
export const ADDPROJECT_FAILURE = 'ADDPROJECT_FAILURE';
